apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceest-ab
  namespace: aceest
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/conditions.aceest-svc-variant-b: >
      [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName":"X-Variant","Values":["B"]}}]
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: aceest-svc
              port:
                number: 80
