apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aceest-ingress-canary
  namespace: aceest
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  # change 0-100
spec:
  rules:
    - host: aceest.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: aceest-svc-canary
                port:
                  number: 80
