apiVersion: v1
kind: Service
metadata:
  name: aceest-svc
  namespace: aceest
spec:
  selector:
    app: aceest-api
    version: stable
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
